# Create Array

* 通过np.array()进行创建
* 常见的一个错误（应该用list来创建，而不是set来创建）
* 手动创建二维数组
* 手动创建二维数组，并指定元素类型
* NumPy的几个特殊数组（np.zero, np.ones, np.empy）
* 用np.arange生成数组
* 用np.linspace创建等差数列

## 通过np.array()进行创建


In [1]:
import numpy as np

a = np.array([2,3,4])
print(a)
print(a.dtype)

b = np.array([1.2, 3.5, 5.1])
print(b)
print(b.dtype)


[2 3 4]
int32
[1.2 3.5 5.1]
float64


## 常见的一个错误（应该用list来创建，而不是用set来创建）

In [2]:
a = np.array(1,2,3,4)

ValueError: only 2 non-keyword arguments accepted

## 手动创建二维数组

In [ ]:
a = np.array([[1.5, 2, 3],[4, 5, 6]])
a.dtype

dtype('float64')

## 手动创建二维数组，并指定数据类型

In [ ]:
a = np.array([[1,2], [3,4]], dtype=complex)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

## numpy的几个特殊数组

也可以说是几个特殊的矩阵，对应着线性代数中的概念。

In [ ]:
# zero
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# ones
np.ones((2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [ ]:
# empty
np.empty((2,3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

## 用np.arange生成数组 

In [ ]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [ ]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

## 用np.linspace()创建等差数列 

In [ ]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
from numpy import pi
x = np.linspace(0, 2*pi, 100)
f = np.sin(x)
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -