# Basic Operations

* 减法
* 常数乘法1
* 常数乘法2
* 元素乘法
* 矩阵x矩阵（第1种，符号）
* 矩阵x矩阵（第2种，函数）
* “*=”操作
* “+=”操作
* dtype不同的矩阵运算
* 元素的和
* 元素的最小值
* 元素的最大值
* 列合计
* 行的最小值
* 行的累积总和 

## 减法 

In [86]:
import numpy as np
a = np.array([20,30,40,50])
b = np.arange(4)
c = a - b
c

array([20, 29, 38, 47])

## 常数乘法1

In [87]:
b ** 2

array([0, 1, 4, 9], dtype=int32)

## 常数乘法2

In [88]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [89]:
a < 35

array([ True,  True, False, False])

## 元素乘法

In [90]:
A = np.array([  [1,1],
                [0,1]])
B = np.array([  [2,0],
                [3,4]])
A * B

array([[2, 0],
       [0, 4]])

## 矩阵x矩阵（第1种，符号）

In [91]:
A @ B

array([[5, 4],
       [3, 4]])

## 矩阵x矩阵（第2种，函数）

In [92]:
A.dot(B)

array([[5, 4],
       [3, 4]])

## “*=”操作

In [93]:
# 如果碰到“AttributeError: module 'numpy.random' has no attribute 'default_rng'”
# 则需升级numpy版本

rg = np.random.default_rng(1)
a = np.ones((2,3), dtype=int)
b = rg.random((2,3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

## “+=”操作

In [94]:
b += a
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [95]:
# dtype不同，且没法转换时，则会报异常！
a += b

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

## dtype不同的矩阵运算

In [ ]:
from numpy import pi
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, pi, 3)
b.dtype.name

'float64'

In [ ]:
c = a + b
c

array([1.        , 2.57079633, 4.14159265])

In [ ]:
c.dtype.name

'float64'

In [ ]:
d = np.exp(c * 1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [ ]:
d.dtype.name

'complex128'

## 元素的和

In [ ]:
a = rg.random((2,3))
a

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

In [ ]:
a.sum()

3.1057109529998157

## 元素的最小值

In [ ]:
a.min()

0.027559113243068367

## 元素的最大值

In [ ]:
a.max()

0.8277025938204418

## 列合计

In [ ]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b.sum(axis=0)

array([12, 15, 18, 21])

## 行的最小值

In [ ]:
b.min(axis=1)

array([0, 4, 8])

## 行的累积总和

In [ ]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)