# Printing Arrays

* 打印一维数组
* 打印二维数组
* 打印三维数组
* 打印数量较多的一维数组
* 打印数量较多的二维数组


In [7]:
# 打印一维数组
import numpy as np
print(np.arange(6))

[0 1 2 3 4 5]


In [8]:
# 打印二维数组
print(np.arange(9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
# 打印三维数组 
print(np.arange(4*4*4).reshape(4,4,4))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]
  [60 61 62 63]]]


In [10]:
# 打印数量较多的一维数组
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [11]:
# 打印数量较多的二维数组
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]
